// <auto-generated />
namespace InstantDelivery.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class whatever2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(whatever2));
        
        string IMigrationMetadata.Id
        {
            get { return "201511011445504_whatever2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
