// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace InstantDelivery.Core.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201510312212515_NewColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
