// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace InstantDelivery.Domain.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CascadeSetNullDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CascadeSetNullDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201511071315597_CascadeSetNullDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
