// <auto-generated />
namespace InstantDelivery.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PackageHistory_OnDeleteSetNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PackageHistory_OnDeleteSetNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201512112059594_PackageHistory_OnDeleteSetNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
